### ISSUE TITLE
Version 1.0.3 doesn't get resolved in AMD machine

### ISSUE THREAD

**Issue by rraagghhu** [crypto-browserify/buffer-xor#17]
Hi, I am hosting my service on AWS ec2 machine. Install command stopped working from yesterday. Let me know if anymore details are required.

- Platform: Linux
- OS: AMD machine
- Node version: 16.20.2
- Package Manager: Yarn 

Log:
> yarn add buffer-xor@1.0.3

yarn add v1.22.22
[1/4] Resolving packages...
[2/4] Fetching packages...
error Error: https://registry.yarnpkg.com/buffer-xor/-/buffer-xor-1.0.3.tgz: Request failed "304 Not Modified"
    at ResponseError.ExtendableBuiltin (/home/ec2-user/.nvm/versions/node/v16.20.2/lib/node_modules/yarn/lib/cli.js:696:66)
    at new ResponseError (/home/ec2-user/.nvm/versions/node/v16.20.2/lib/node_modules/yarn/lib/cli.js:802:124)
    at Request.<anonymous> (/home/ec2-user/.nvm/versions/node/v16.20.2/lib/node_modules/yarn/lib/cli.js:66750:16)
    at Request.emit (node:events:513:28)
    at Request.module.exports.Request.onRequestResponse (/home/ec2-user/.nvm/versions/node/v16.20.2/lib/node_modules/yarn/lib/cli.js:142287:10)
    at ClientRequest.emit (node:events:513:28)
    at HTTPParser.parserOnIncomingClient (node:_http_client:693:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
    at TLSSocket.socketOnData (node:_http_client:534:22)
    at TLSSocket.emit (node:events:513:28)
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

**Comment by rraagghhu** [comment]
Seems like instances from Mumbai are facing this issue 

https://github.com/yarnpkg/yarn/issues/9118
